# -*- coding: utf-8 -*-
"""
DS2 Radar - Offset Finder, STAGE 2 (validate & generate config).

Run this AFTER you rebooted the game (that's the whole point: it proves the
pointer chain is permanent). It reads finder_state.json (from stage 1),
keeps only the chains that still resolve to your LIVE position (the ones that
move when you walk), verifies the area addresses, and writes config.generated.ini.

Rename config.generated.ini to config.ini and drop it next to server3d.py.

Requirements: game running (rebooted), be in an OPEN area, PS4CheaterNeo CLOSED.
"""
import asyncio, struct, threading, queue, os, json, time
import tkinter as tk

_DIR   = os.path.dirname(os.path.abspath(__file__))
ROOT   = os.path.dirname(_DIR)                      # package root
STATE  = os.path.join(_DIR, "finder_state.json")
OUT    = os.path.join(ROOT, "config.generated.ini") # next to config.ini
LIVE_S = 16
msg_q = queue.Queue()
W,H = 740,520

async def ru64(ps4,pid,a):
    d=await ps4.read_memory(pid,a,8)
    if isinstance(d,tuple): d=d[-1]
    if not d or len(d)<8: return None
    return struct.unpack("<Q",d[:8])[0]

async def resolve(ps4,pid,base,so,offs):
    a=base+so
    for o in offs:
        v=await ru64(ps4,pid,a)
        if v is None or v<0x10000 or v>0x800000000: return None
        a=v+o
    return a

async def readpos(ps4,pid,a):
    d=await ps4.read_memory(pid,a,16)
    if isinstance(d,tuple): d=d[-1]
    if not d or len(d)<16: return None
    return struct.unpack("<4f",d[:16])   # (w,x,y,z)

def plausible(p):
    if not p: return False
    w,x,y,z=p
    return 0.9<w<1.1 and all(abs(v)<3000 for v in (x,y,z)) and any(abs(v)>0.01 for v in (x,y,z))

def write_config(ip,static_off,offsets,area_offs,version):
    L=["# DS2 Radar 3D - config generated by finder_validate.py","",
       "[ps4]",f"ip = {ip}","",
       "[position]","# static pointer chain -> position block [1.0, X, Y, Z]",
       f"static_off = 0x{static_off:X}","offsets    = "+", ".join(f"0x{o:X}" for o in offsets),"",
       "[area]","# addresses of the current map name \"MM_NN\" (offsets from eboot_base)",
       "offsets = "+", ".join(f"0x{o:X}" for o in area_offs),"",
       "[info]","game    = Dark Souls II: Scholar of the First Sin",f"version = {version}",""]
    with open(OUT,"w",encoding="utf-8") as f: f.write("\n".join(L))

def worker():
    try:
        import ps4debug
        loop=asyncio.new_event_loop(); asyncio.set_event_loop(loop)
        if not os.path.exists(STATE):
            msg_q.put(("err","finder_state.json missing - run finder_scan.py first")); return
        st=json.load(open(STATE,encoding="utf-8"))
        chains=st["chains"]; area_offs=st["area_offsets"]; ip=st.get("ip","192.168.1.104")
        msg_q.put(("info",f"loaded {len(chains)} chains, {len(area_offs)} area addrs"))
        ps4=ps4debug.PS4Debug(ip)
        if asyncio.iscoroutine(ps4): ps4=loop.run_until_complete(ps4)
        procs=loop.run_until_complete(ps4.get_processes())
        pid=next((getattr(p,"pid",None) for p in procs if "eboot" in str(getattr(p,"name",""))),None)
        if pid is None: msg_q.put(("err","DS2 not found")); return
        maps=loop.run_until_complete(ps4.get_process_maps(pid))
        exe=[m.start for m in maps if 'executable' in str(getattr(m,'name','') or '')]
        base=min(exe) if exe else 0x400000
        msg_q.put(("info",f"eboot_base=0x{base:X}"))

        # FASE 1: resolve + keep valid (store resolved addr)
        valid=[]
        for i,ch in enumerate(chains):
            if i%25==0: msg_q.put(("phase",("RESOLVING CHAINS",f"{i}/{len(chains)}",f"valid={len(valid)}",0)))
            so,offs=ch[0],ch[1]
            a=loop.run_until_complete(resolve(ps4,pid,base,so,offs))
            if a is None: continue
            if plausible(loop.run_until_complete(readpos(ps4,pid,a))): valid.append((so,offs,a))
        msg_q.put(("info",f"valid after reboot: {len(valid)}"))
        if not valid: open(OUT+".fail","w").write("0 valid"); msg_q.put(("done","0 valid - chains broke, rescan")); return

        # FASE 2: walk -> which addresses move
        addrs=sorted(set(a for _,_,a in valid))
        hist={a:[] for a in addrs}; t0=time.time()
        while time.time()-t0<LIVE_S:
            left=int(LIVE_S-(time.time()-t0))+1
            msg_q.put(("phase",("WALK IN CIRCLES",f"don't stop {left}s",f"addresses={len(addrs)}",0)))
            for a in addrs:
                p=loop.run_until_complete(readpos(ps4,pid,a))
                hist[a].append((p[1],p[2],p[3]) if plausible(p) else None)
            time.sleep(0.12)
        moving=set()
        for a in addrs:
            seq=[v for v in hist[a] if v]
            if len(seq)<6: continue
            steps=[((seq[j][0]-seq[j-1][0])**2+(seq[j][2]-seq[j-1][2])**2)**0.5 for j in range(1,len(seq))]
            path=sum(s for s in steps if s<10); mx=max(steps) if steps else 0
            if path>2.0 and mx<25 and len(seq)>=0.5*len(hist[a]): moving.add(a)
        surv=[(len(offs),so,offs) for so,offs,a in valid if a in moving]
        surv.sort()
        msg_q.put(("info",f"moving addresses: {len(moving)}  surviving chains: {len(surv)}"))
        if not surv: msg_q.put(("done","0 chains tracked - walk more / rescan")); return

        # verify area offsets still resolve to a "DD_DD" string
        good_area=[]
        for off in area_offs:
            d=loop.run_until_complete(ps4.read_memory(pid,base+off,5))
            if isinstance(d,tuple): d=d[-1]
            if d and len(d)>=5 and d[2:3]==b"_" and d[0:2].isdigit() and d[3:5].isdigit():
                good_area.append(off)
        if not good_area: good_area=area_offs   # fallback: keep them
        msg_q.put(("info",f"area addrs verified: {len(good_area)}"))

        _,so,offs=surv[0]
        ver=".".join(str(v) for v in st.get("areas",[])) or "unknown"
        write_config(ip,so,offs,good_area,"generated (fill your CUSA/patch here)")
        msg_q.put(("done",f"OK! static 0x{so:X} | "+" ".join(f"0x{o:X}" for o in offs)+"  -> config.generated.ini"))
    except Exception as e:
        import traceback; msg_q.put(("err",f"{e} | {traceback.format_exc()[:180]}"))

class UI:
    def __init__(self):
        self.root=tk.Tk(); self.root.title("DS2 Radar - Finder (Stage 2: Validate)"); self.root.configure(bg="#101216")
        self.root.geometry(f"{W}x{H}+50+40")
        self.cv=tk.Canvas(self.root,width=W,height=H,bg="#101216",highlightthickness=0); self.cv.pack()
        self.state=("CONNECTING...","","",0); self.info=""; self.done=False
        threading.Thread(target=worker,daemon=True).start(); self.tick(); self.root.mainloop()
    def tick(self):
        while True:
            try:k,p=msg_q.get_nowait()
            except queue.Empty:break
            if k=="phase":self.state=p
            elif k=="info":self.info=str(p)
            elif k=="done":self.state=("DONE!",str(p)[:52],"rename to config.ini",0);self.done=True
            elif k=="err":self.state=("ERROR",str(p)[:64],"",0)
        self.draw();self.root.after(100,self.tick)
    def draw(self):
        cv=self.cv;cv.delete("all");t,l1,l2,s=self.state
        col="#3fd07f" if self.done else "#ffd23f"
        cv.create_text(W/2,110,text=t,fill=col,font=("Consolas",20,"bold"))
        cv.create_text(W/2,185,text=l1,fill="#e8eefc",font=("Consolas",15,"bold"))
        cv.create_text(W/2,225,text=l2,fill="#9fb0cc",font=("Consolas",13))
        if s: cv.create_text(W/2,320,text=str(s),fill=col,font=("Consolas",52,"bold"))
        cv.create_text(W/2,H-28,text=self.info,fill="#5b6b86",font=("Consolas",10))

if __name__=="__main__":
    UI()
